name: base_station
description: A sample command-line application.
version: 1.0.0
publish_to: none
repository: https://github.com/BinghamtonRover/Base-Station

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  burt_network:
    git:
      url: https://github.com/BinghamtonRover/Rover-Code.git
      path: burt_network

dev_dependencies:
  test: ^1.24.0
  very_good_analysis: ^6.0.0
